DASH = "\u2012"
DOT = "\u00b7"

MORSE = {
    "a": f"{DOT}{DASH}",
    "b": f"{DASH}{DOT}{DOT}{DOT}",
    "c": f"{DASH}{DOT}{DASH}{DOT}",
    "d": f"{DASH}{DOT}{DOT}",
    "e": f"{DOT}",
    "f": f"{DOT}{DOT}{DASH}{DOT}",
    "g": f"{DASH}{DASH}{DOT}",
    "h": f"{DOT}{DOT}{DOT}{DOT}",
    "i": f"{DOT}{DOT}",
    "j": f"{DOT}{DASH}{DASH}{DASH}",
    "k": f"{DASH}{DOT}{DASH}",
    "l": f"{DOT}{DASH}{DOT}{DOT}",
    "m": f"{DASH}{DASH}",
    "n": f"{DASH}{DOT}",
    "o": f"{DASH}{DASH}{DASH}",
    "p": f"{DOT}{DASH}{DASH}{DOT}",
    "q": f"{DASH}{DASH}{DOT}{DASH}",
    "r": f"{DOT}{DASH}{DOT}",
    "s": f"{DOT}{DOT}{DOT}",
    "t": f"{DASH}",
    "u": f"{DOT}{DOT}{DASH}",
    "v": f"{DOT}{DOT}{DOT}{DASH}",
    "w": f"{DOT}{DASH}{DASH}",
    "x": f"{DASH}{DOT}{DOT}{DASH}",
    "y": f"{DASH}{DOT}{DASH}{DASH}",
    "z": f"{DASH}{DASH}{DOT}{DOT}",
    "1": f"{DOT}{DASH}{DASH}{DASH}{DASH}",
    "2": f"{DOT}{DOT}{DASH}{DASH}{DASH}",
    "3": f"{DOT}{DOT}{DOT}{DASH}{DASH}",
    "4": f"{DOT}{DOT}{DOT}{DOT}{DASH}",
    "5": f"{DOT}{DOT}{DOT}{DOT}{DOT}",
    "6": f"{DASH}{DOT}{DOT}{DOT}{DOT}",
    "7": f"{DASH}{DASH}{DOT}{DOT}{DOT}",
    "8": f"{DASH}{DASH}{DASH}{DOT}{DOT}",
    "9": f"{DASH}{DASH}{DASH}{DASH}{DOT}",
    "0": f"{DASH}{DASH}{DASH}{DASH}{DASH}",
}